[project]
name = "aidams-lab2-destal-montluc-riekhakainen-magretdelord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "joblib>=1.6.0",
    "jupyterlab>=4.6.4",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "openpyxl>=3.1.5",
    "optuna>=5.0.0",
    "optuna-integration[mlflow]>=5.0.0",
    "pandas>=3.0.6",
    "pandera>=0.33.1",
    "scikit-learn>=1.9.1",
]
